# Generated by Django 5.1.4 on 2024-12-30 13:15

import ResumeSageApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoggedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[ResumeSageApp.models.custom_email_validator],
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "password",
                    models.CharField(
                        max_length=250,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                ("file_name", models.CharField(blank=True, default="", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"abstract": False,},
        ),
    ]
